#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name=$(basename $buildpack_url)
    buildpack_commit="$2"

    git clone $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
    pushd $BUILDPACK_INSTALL_PATH/$buildpack_name 2>&1 >/dev/null
        git checkout --quiet $buildpack_commit
    popd 2>&1 >/dev/null
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/ddollar/heroku-buildpack-multi.git         6e79094
download_buildpack https://github.com/heroku/heroku-buildpack-ruby.git           v129
download_buildpack https://github.com/heroku/heroku-buildpack-nodejs.git         v62
download_buildpack https://github.com/heroku/heroku-buildpack-java.git           v32
download_buildpack https://github.com/heroku/heroku-buildpack-gradle.git         24a8ebe
download_buildpack https://github.com/heroku/heroku-buildpack-grails.git         1ef927d
download_buildpack https://github.com/heroku/heroku-buildpack-play.git           9c137b4
download_buildpack https://github.com/heroku/heroku-buildpack-python.git         v53
download_buildpack https://github.com/heroku/heroku-buildpack-php.git            v50
download_buildpack https://github.com/heroku/heroku-buildpack-clojure.git        v63
download_buildpack https://github.com/heroku/heroku-buildpack-scala.git          v43
download_buildpack https://github.com/heroku/heroku-buildpack-go.git             0e20030
