#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name=$(basename $buildpack_url)
    buildpack_commit="$2"

    git clone $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
    pushd $BUILDPACK_INSTALL_PATH/$buildpack_name 2>&1 >/dev/null
        git checkout --quiet $buildpack_commit
    popd 2>&1 >/dev/null
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/ddollar/heroku-buildpack-multi.git         9350571
download_buildpack https://github.com/heroku/heroku-buildpack-ruby.git           v127
download_buildpack https://github.com/heroku/heroku-buildpack-nodejs.git         v60
download_buildpack https://github.com/heroku/heroku-buildpack-java.git           v28
download_buildpack https://github.com/heroku/heroku-buildpack-gradle.git         743f73c
download_buildpack https://github.com/heroku/heroku-buildpack-grails.git         1ef927d
download_buildpack https://github.com/heroku/heroku-buildpack-play.git           ceede86
download_buildpack https://github.com/heroku/heroku-buildpack-python.git         v52
download_buildpack https://github.com/heroku/heroku-buildpack-php.git            v43
download_buildpack https://github.com/heroku/heroku-buildpack-clojure.git        bc2bfd8
download_buildpack https://github.com/heroku/heroku-buildpack-scala.git          v41
download_buildpack https://github.com/heroku/heroku-buildpack-go.git             b261aab
